# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - DPhelpdesk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://aiacr2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8dd7510aec904fa1857ffb855bbd621a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_054536060063446a8aebe6bd4ba47a5e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: aiacr2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8dd7510aec904fa1857ffb855bbd621a }}/latest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'DPhelpdesk'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c48cf02daf74f8b92e89e5d88b6cda6 }}
        images: 'aiacr2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8dd7510aec904fa1857ffb855bbd621a }}/latest:${{ github.sha }}'